config/routes.rb
Rails.application.routes.draw do
  resources :songs do
    collection do  #creates end point '/songs/search'
      post :search, to: 'songs#search'
      post :addedsongs, to: 'songs#addedsongs'
    end
  end
  
  get 'sessions/new'

  resources :users, :except => [:index, :edit, :update, :show]
  resources :sessions, :only => [:new, :create, :destroy]

  get '/users/profile', to: 'users#show'
  root to: 'songs#index'

  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  
  
  post '/playlists/:playlist_id', to: 'playlist_song#show', as: :show_playlist_songs
  get '/playlists/:playlist_id/songs/:song_id/', to:'playlist_song#add' , as: :add_to_playlist
  
  scope controller: :playlists do
    delete '/playlists/:id' => :destroy, as: :delete_playlist
    post '/playlists' => :create, as: :create_playlist
    get '/playlists' => :show, as: :show_playlist
    post '/playlists/songs/:song_id' => :show, as: :show_playlist_add
    post '/search_playlist'=> :search
    get '/playlists/new' => :new
  end

  
  

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :songs,dependent: :destroy
    has_many :playlists, dependent: :destroy
    has_secure_password
    validates_confirmation_of :password
    validates :username, presence: true, length: {minimum: 5}
    validates :email, presence: true, :uniqueness => { :case_sensitive => false }, format: { with: URI::MailTo::EMAIL_REGEXP } 
    validates :phone_no, presence: true, length: {minimum: 10, maximum: 10}, :uniqueness => { :case_sensitive => false }
    validates :type_of_user, :inclusion => {:in => [true, false]}
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :edit, :update, :destroy]
  before_action :require_same_user, only: [ :edit, :update, :destroy]
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    puts "======================================"
    puts "The session id is #{session[:user_id]}"
    puts "======================================"
    @user = User.find_by_id(session[:user_id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to signin_path, notice: 'Account successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  
  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    session[:user_id] = nil
    current_user = nil
    redirect_to songs_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by_id(params[:id])
      require_same_user
      #redirect_to signin_path unless @user #for a route that does not exist redirect it back to home page
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :phone_no, :type_of_user, :password, :password_confirmation)
    end

    def require_same_user
      
      puts "======================================"
      puts "The session id is #{session[:user_id]}"
      if @user 
      puts "The current user id is #{@user.id}"
      end
      puts Time.now
      puts logged_in?
      puts "======================================"
      require_user
      if logged_in? && current_user != @user #session_current_user is is inherited from application controller
        flash[:notice] = "You cannot perform such actions"
        redirect_to songs_path 
      
      end
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone_no %><br>
    <%= f.number_field :phone_no %>
  </div>
   <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %><br>
    <%= f.label :confirm_password %><br>
    <%= f.password_field :password_confirmation %>
  </div>
 <!-- If song_provider then its true else its false-->
  <div class="field">
    <%= f.label :type_of_user %><br/>
    <%= f.label :type_of_user, "Song_Consumer", :value => "Song_Consumer"  %> 
    <%= f.radio_button :type_of_user, false %><br>
    <%= f.label :type_of_user, "Song_Provider", :value => "Song_Provider" %> &nbsp
    <%= f.radio_button :type_of_user, true  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Phone no</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.phone_no %></td>
        <!--<td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>SIGNUP NEW USER</h1>

<%= render 'form' %>

<button><%= link_to 'SignIn', signin_path %></button>

app/views/users/show.html.erb
<h1> PROFILE PAGE </h1>


<p id="notice"><%= notice %></p>
<% if @user %>
<p class="display-details">
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p class="display-details">
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p class="display-details">
  <strong>Phone no:</strong>
  <%= @user.phone_no %>
</p>
<p class="display-details">
  <strong>User Type:</strong>
  <% if @user.type_of_user %>
  Song_Provider 
  <% else %>
  Song_Consumer
  <%end%>
</p>


  <% if @user.type_of_user %>
  <button>
  <%= link_to 'Add New Song', new_song_path %>
  </button> |
  <button>
  <%= link_to 'View/Edit Song ', addedsongs_songs_path, method: :post%>
  </button> |
  <%end%>

<button>
 <%= link_to 'Logout', signout_path, method: :delete, data: { confirm: 'Are you sure?' } %> 
</button> |
<button>
<%= link_to 'Delete Your Account', user_path(current_user), method: :delete, data: { confirm: 'Are you sure? You Want to delete account?' } %>
</button>

<%else%>
<%controller.redirect_to signin_path%>
<%end%>