config/routes.rb
Rails.application.routes.draw do
  resources :songs do
    collection do  #creates end point '/songs/search'
      post :search, to: 'songs#search'
      post :addedsongs, to: 'songs#addedsongs'
    end
  end
  
  get 'sessions/new'

  resources :users, :except => [:index, :edit, :update, :show]
  resources :sessions, :only => [:new, :create, :destroy]

  get '/users/profile', to: 'users#show'
  root to: 'songs#index'

  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  
  
  post '/playlists/:playlist_id', to: 'playlist_song#show', as: :show_playlist_songs
  get '/playlists/:playlist_id/songs/:song_id/', to:'playlist_song#add' , as: :add_to_playlist
  
  scope controller: :playlists do
    delete '/playlists/:id' => :destroy, as: :delete_playlist
    post '/playlists' => :create, as: :create_playlist
    get '/playlists' => :show, as: :show_playlist
    post '/playlists/songs/:song_id' => :show, as: :show_playlist_add
    post '/search_playlist'=> :search
    get '/playlists/new' => :new
  end

  
  

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
    belongs_to :user
    validate :upper_case_song_name, on: :create
    has_many :playlist_song, dependent: :destroy
    has_many :songs, through: :playlist_song

    def upper_case_song_name
        self.name = name.upcase
    end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
    skip_before_action :verify_authenticity_token, only: [:create, :search]
    before_action :set_playlist, only: [ :destroy]
    before_action :set_playlist_show, only: [:show]
    def new
        @playlist = Playlist.new
    end

    def create
        @playlist = current_user.playlists.create(name: params[:name])
        respond_to do |format|
            if @playlist.save
              format.html { redirect_to show_playlist_path, notice: 'Playlist was successfully created.' }
            else
              format.html { render playlist }
            end
        end
    end

    def show
        @content_text = " Your Playlists"
    end

    def destroy
        @playlist.destroy
        respond_to do |format|
            format.html { redirect_to show_playlist_path, notice: 'Playlist was successfully destroyed.' }
        end
    end

    def search
        search_playlist = Playlist.where(name: params[:name].upcase)
        @playlists = search_playlist
        if search_playlist
            @content_text = "Playlist searched for"
            render "show"
        else
            @content_text = "Playlist not found"
            redirect_to show_playlist_path
        end
    end
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist_show
      @playlists = Playlist.where(user_id: current_user)
    end
    def set_playlist
        @playlist = Playlist.find(params[:id])
    end
    
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/new.html.erb
<h1>Create Your Playlist </h1>
<form action="/playlists" method="post">
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


 <input name="name" type="text"  placeholder="Playlist Name"/>
 <br>
  <input type="submit" value="Create">
</form>

<h2>View Your Playlist</h2>
<button><%= link_to 'Your Playlists ',  show_playlist_path %></button>

app/views/playlists/show.html.erb
<p id="error"><%= notice %></p>

<h1><%= @content_text %></h1>

<form action="/search_playlist" method="post">
  
  <input type="text"  name="name" placeholder = "Search playlist">
  <input type="submit" value="Search">
</form>
<button><%= link_to 'Create new playlist',playlists_new_path %></button>
<div class="grid-container">
 <% @playlists.reverse.each do |playlist| %>
  <div class="grid-item">
  <h4><%= playlist.name %></h4>
  <% playlist.songs.reverse.each do |song| %>
  <p><%= song.name %></p>
  <%end%>
  <%if params[:song_id]%>
    <p><p><%= link_to 'Add In This playlist', add_to_playlist_path(song_id: params[:song_id], playlist_id: playlist.id )%></p> </p>
  <%end%>
  <p><p><%= link_to 'View Playlist Songs', show_playlist_songs_path(playlist),method: :post %></p> </p>
  <p><p><%= link_to 'Delete', delete_playlist_path(playlist), method: :delete, data: { confirm: 'Are you sure? You Want to delete playlist?' } %></p> </p>
</div>

<% end %>
</div>