config/routes.rb
Rails.application.routes.draw do
  resources :songs do
    collection do  #creates end point '/songs/search'
      post :search, to: 'songs#search'
      post :addedsongs, to: 'songs#addedsongs'
    end
  end
  
  get 'sessions/new'

  resources :users, :except => [:index, :edit, :update, :show]
  resources :sessions, :only => [:new, :create, :destroy]

  get '/users/profile', to: 'users#show'
  root to: 'songs#index'

  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  
  
  post '/playlists/:playlist_id', to: 'playlist_song#show', as: :show_playlist_songs
  get '/playlists/:playlist_id/songs/:song_id/', to:'playlist_song#add' , as: :add_to_playlist
  
  scope controller: :playlists do
    delete '/playlists/:id' => :destroy, as: :delete_playlist
    post '/playlists' => :create, as: :create_playlist
    get '/playlists' => :show, as: :show_playlist
    post '/playlists/songs/:song_id' => :show, as: :show_playlist_add
    post '/search_playlist'=> :search
    get '/playlists/new' => :new
  end

  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyMusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul class="navbar">
  <li class="nav-component"><%= link_to MyMusicApp, songs_path %></li>
  
  <% if logged_in?%>
  <li class="nav-component" style="float:right">
  <%=link_to 'playlist', playlists_new_path %>
  </li>
  <li class="nav-component" style="float:right">
  <%=link_to current_user.username, users_profile_path %></li>
  <%else%>
  <li class="nav-component" style="float:right"><%=link_to 'Login', signin_path %></li>
  <%end%>

  
</ul>
<div class="center-of-page">
<%= yield %>
</div>
</body>
</html>